JUPYTER IS BEST FOR DATA ANALYSIS

In [2]:
import numpy as np
import pandas as pd
csv1=pd.read_csv("C:\\Users\\PANDEY JI\\Desktop\\PYTHON\\IPL.csv")
csv1

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
3,4,Indore,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0
5,6,Hyderabad,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,0,9
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4

In [4]:
csv1.shape

(10, 9)

In [5]:
csv1.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              10 non-null     int64
 1   city            10 non-null     str
 2   team1           10 non-null     str
 3   team2           10 non-null     str
 4   toss_winner     10 non-null     str
 5   toss_decision   10 non-null     str
 6   winner          10 non-null     str
 7   win_by_runs     10 non-null     int64
 8   win_by_wickets  10 non-null     int64
dtypes: int64(3), str(6)
memory usage: 852.0 bytes

In [6]:
csv1.head() #few rows from top

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
3,4,Indore,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0

In [7]:
csv1.head().shape

(5, 9)

In [8]:
csv1.head(3) #3 rows from top

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10

In [9]:
csv1.tail() #few rows from bottom

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
5,6,Hyderabad,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,0,9
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4

In [10]:
csv1.tail(3) #3 rows from bottom

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4

In [11]:
csv1.describe() # statisticalvalues for numeric values column

             id  win_by_runs  win_by_wickets
count  10.00000    10.000000       10.000000
mean    5.50000    14.700000        4.800000
std     3.02765    31.087868        3.823901
min     1.00000     0.000000        0.000000
25%     3.25000     0.000000        1.000000
50%     5.50000     0.000000        5.000000
75%     7.75000    11.250000        7.750000
max    10.00000    97.000000       10.000000

In [12]:
csv1['city'] #show a perticular column

0    Hyderabad
1         Pune
2       Rajkot
3       Indore
4    Bangalore
5    Hyderabad
6       Mumbai
7       Indore
8         Pune
9       Mumbai
Name: city, dtype: str

In [13]:
csv1['city'][5] #show a perticular column with perticular row

'Hyderabad'

In [14]:
csv1['city'][5]=0 #change a perticular column & perticular row's value with warning.original file wont be changed

C:\Users\PANDEY JI\AppData\Local\Temp\ipykernel_6564\569454076.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  csv1['city'][5]=0 #change a perticular column & perticular row's value with warning.original file wont be changed

TypeError: Invalid value '0' for dtype 'str'. Value should be a string or missing value, got 'int' instead.

In [15]:
csv1

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
3,4,Indore,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0
5,6,Hyderabad,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,0,9
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4

In [16]:
csv1.to_csv('matches_1.csv') #create a new file with changed data

In [17]:
csv1.index #info about indexes

RangeIndex(start=0, stop=10, step=1)

In [18]:
csv1.columns

Index(['id', 'city', 'team1', 'team2', 'toss_winner', 'toss_decision',
       'winner', 'win_by_runs', 'win_by_wickets'],
      dtype='str')

In [19]:
csv1.T #rows and columns will get exchanged

,0,1,2,3,4,5,6,7,8,9
id,1,2,3,4,5,6,7,8,9,10
city,Hyderabad,Pune,Rajkot,Indore,Bangalore,Hyderabad,Mumbai,Indore,Pune,Mumbai
team1,Sunrisers Hyderabad,Mumbai Indians,Gujarat Lions,Rising Pune Supergiant,Royal Challengers Bangalore,Gujarat Lions,Kolkata Knight Riders,Royal Challengers Bangalore,Delhi Daredevils,Sunrisers Hyderabad
team2,Royal Challengers Bangalore,Rising Pune Supergiant,Kolkata Knight Riders,Kings XI Punjab,Delhi Daredevils,Sunrisers Hyderabad,Mumbai Indians,Kings XI Punjab,Rising Pune Supergiant,Mumbai Indians
toss_winner,Royal Challengers Bangalore,Rising Pune Supergiant,Kolkata Knight Riders,Kings XI Punjab,Royal Challengers Bangalore,Sunrisers Hyderabad,Mumbai Indians,Royal Challengers Bangalore,Rising Pune Supergiant,Mumbai Indians
toss_decision,field,field,field,field,bat,field,field,bat,field,field
winner,Sunrisers Hyderabad,Rising Pune Supergiant,Kolkata Knight Riders,Kings XI Punjab,Royal Challengers Bangalore,Sunrisers Hyderabad,Mumbai Indians,Kings XI Punjab,Delhi Daredevils,Mumbai Indians
win_by_runs,35,0,0,0,15,0,0,0,97,0
win_by_wickets,0,7,10,6,0,9,4,8,0,4

In [20]:
csv1.head()

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
3,4,Indore,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0

In [21]:
csv1.sort_index(axis=0,ascending = False) #reverse order index axix=0 is row and axis=1 is column

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4
5,6,Hyderabad,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,0,9
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0
3,4,Indore,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0

In [22]:
csv1.sort_index(axis=1,ascending = False) #reverse order column

,winner,win_by_wickets,win_by_runs,toss_winner,toss_decision,team2,team1,id,city
0,Sunrisers Hyderabad,0,35,Royal Challengers Bangalore,field,Royal Challengers Bangalore,Sunrisers Hyderabad,1,Hyderabad
1,Rising Pune Supergiant,7,0,Rising Pune Supergiant,field,Rising Pune Supergiant,Mumbai Indians,2,Pune
2,Kolkata Knight Riders,10,0,Kolkata Knight Riders,field,Kolkata Knight Riders,Gujarat Lions,3,Rajkot
3,Kings XI Punjab,6,0,Kings XI Punjab,field,Kings XI Punjab,Rising Pune Supergiant,4,Indore
4,Royal Challengers Bangalore,0,15,Royal Challengers Bangalore,bat,Delhi Daredevils,Royal Challengers Bangalore,5,Bangalore
5,Sunrisers Hyderabad,9,0,Sunrisers Hyderabad,field,Sunrisers Hyderabad,Gujarat Lions,6,Hyderabad
6,Mumbai Indians,4,0,Mumbai Indians,field,Mumbai Indians,Kolkata Knight Riders,7,Mumbai
7,Kings XI Punjab,8,0,Royal Challengers Bangalore,bat,Kings XI Punjab,Royal Challengers Bangalore,8,Indore
8,Delhi Daredevils,0,97,Rising Pune Supergiant,field,Rising Pune Supergiant,Delhi Daredevils,9,Pune
9,Mumbai Indians,4,0,Mumbai Indians,field,Mumbai Indians,Sunrisers Hyderabad,10,Mumbai

In [23]:
csv2=csv1
#its a view mode so csv2 will basically point at csv1's memory location.
#Any changes made in csv2 will be reflected in csv1 as well.

In [24]:
csv2['city'][0]="prayagraj"

C:\Users\PANDEY JI\AppData\Local\Temp\ipykernel_6564\1436405055.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  csv2['city'][0]="prayagraj"

In [25]:
csv2.head()

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
3,4,Indore,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0

In [26]:
csv1.head()

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
3,4,Indore,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0

In [27]:
csv3=csv1.copy() # Its a copy mode in which a copy of csv1 will be copied in csv3
#and any changes made in csv3 will not be reflected in csv1

In [28]:
csv3['city'][1]='GreNo'

C:\Users\PANDEY JI\AppData\Local\Temp\ipykernel_6564\3909947299.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  csv3['city'][1]='GreNo'

In [29]:
csv1.head() #no change in original file csv1

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
3,4,Indore,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0

In [30]:
csv3.head() #only changes are made in csv3

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
3,4,Indore,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0

In [32]:
csv2.loc[3,'city']='nainital' #no error will show.

In [33]:
csv2

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0
5,6,Hyderabad,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,0,9
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4

In [34]:
csv2[0]='pooja'

In [35]:
csv2

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,0
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0,pooja
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7,pooja
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10,pooja
3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6,pooja
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0,pooja
5,6,Hyderabad,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,0,9,pooja
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4,pooja
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8,pooja
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0,pooja
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4,pooja

In [36]:
csv2.drop(5) #dropped the 5th row

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,0
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0,pooja
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7,pooja
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10,pooja
3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6,pooja
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0,pooja
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4,pooja
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8,pooja
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0,pooja
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4,pooja

In [37]:
csv2.drop(0,axis=1) #dropped the column named 0.

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0
5,6,Hyderabad,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,0,9
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4

In [38]:
csv2.loc[[3,4],['city','winner']]

        city                       winner
3   nainital              Kings XI Punjab
4  Bangalore  Royal Challengers Bangalore

In [39]:
csv2.loc[[3,4],:]

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,0
3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6,pooja
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0,pooja

In [40]:
csv2.loc[(csv2['toss_decision'] =='field')]

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,0
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0,pooja
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7,pooja
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10,pooja
3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6,pooja
5,6,Hyderabad,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,0,9,pooja
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4,pooja
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0,pooja
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4,pooja

In [41]:
csv2.loc[(csv2['toss_decision'] =='field')& (csv2['city'] =='Mumbai' )]

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,0
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4,pooja
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4,pooja

In [42]:
csv2.iloc[0,6] #show 0th row and 6th column value

'Sunrisers Hyderabad'

In [43]:
csv2.iloc[[0,6],[2,5]]

                   team1 toss_decision
0    Sunrisers Hyderabad         field
6  Kolkata Knight Riders         field

In [44]:
csv2.head(3)

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,0
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0,pooja
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7,pooja
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10,pooja

In [45]:
csv2.drop([1]) #delete row 1

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,0
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0,pooja
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10,pooja
3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6,pooja
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0,pooja
5,6,Hyderabad,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,0,9,pooja
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4,pooja
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8,pooja
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0,pooja
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4,pooja

In [46]:
csv2.drop([0],axis=1) #delete column named 0

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0
5,6,Hyderabad,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,0,9
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4

In [47]:
csv2 #column 0 is not deleted from original data

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,0
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0,pooja
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7,pooja
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10,pooja
3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6,pooja
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0,pooja
5,6,Hyderabad,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,0,9,pooja
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4,pooja
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8,pooja
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0,pooja
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4,pooja

In [48]:
#csv2=csv2.drop([0],axis=1) # column 0 get deleted permanently from original file. (1st method)
csv2.drop([0],axis=1,inplace=True) # column 0 get deleted permanently from original file.(2nd method)

In [49]:
csv2

,id,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,0,7
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,0,10
3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,0,6
4,5,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,15,0
5,6,Hyderabad,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,0,9
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,0,8
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,Delhi Daredevils,97,0
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,0,4

In [50]:
csv2.drop(['winner','toss_decision'],axis=1,inplace=True)

In [51]:
csv2.drop([2,4],axis=0,inplace=True)

In [52]:
csv2 #row 2 and 4 and colum winner and toss_decision are deleted from original file permanently

,id,city,team1,team2,toss_winner,win_by_runs,win_by_wickets
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,0,7
3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,0,6
5,6,Hyderabad,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,0,9
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,0,4
7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,0,8
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,97,0
9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,0,4

In [53]:
csv2.head()

,id,city,team1,team2,toss_winner,win_by_runs,win_by_wickets
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,35,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,0,7
3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,0,6
5,6,Hyderabad,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,0,9
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,0,4

In [54]:
csv2.reset_index() #to reset index but one column index is also there.

,index,id,city,team1,team2,toss_winner,win_by_runs,win_by_wickets
0,0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,35,0
1,1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,0,7
2,3,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,0,6
3,5,6,Hyderabad,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,0,9
4,6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,0,4
5,7,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,0,8
6,8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,97,0
7,9,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,0,4

In [55]:
csv2.reset_index(drop=True,inplace=True) #index column will be removed

In [56]:
csv2['win_by_runs']=None #make this column value as None

In [57]:
csv2

,id,city,team1,team2,toss_winner,win_by_runs,win_by_wickets
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,None,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,None,7
2,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,None,6
3,6,Hyderabad,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,None,9
4,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,None,4
5,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,None,8
6,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,None,0
7,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,None,4

In [58]:
csv2.isnull() #return True for Null/None values rest will be False

      id   city  team1  team2  toss_winner  win_by_runs  win_by_wickets
0  False  False  False  False        False         True           False
1  False  False  False  False        False         True           False
2  False  False  False  False        False         True           False
3  False  False  False  False        False         True           False
4  False  False  False  False        False         True           False
5  False  False  False  False        False         True           False
6  False  False  False  False        False         True           False
7  False  False  False  False        False         True           False

In [59]:
csv2['win_by_runs'].isnull() #return True for Null/None values

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
Name: win_by_runs, dtype: bool

In [60]:
csv2['win_by_runs']=99 #make this column value as 99

In [61]:
csv2

,id,city,team1,team2,toss_winner,win_by_runs,win_by_wickets
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,99,0
1,2,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,99,7
2,4,nainital,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,99,6
3,6,Hyderabad,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,99,9
4,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,99,4
5,8,Indore,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,99,8
6,9,Pune,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,99,0
7,10,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,99,4

In [62]:
df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
 "toy": [np.nan, 'Batmobile', 'Bullwhip'],
 "born": [pd.NaT, pd.Timestamp("1940-04-25"),
 pd.NaT]})

In [63]:
df

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [64]:
df.dropna() #drop rows and column having values NA

     name        toy       born
1  Batman  Batmobile 1940-04-25

In [65]:
df.dropna(how='all') #wont drop till all values of row or column is NA

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [66]:
df1 = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
 "toy": [np.nan, np.nan, np.nan],
 "born": [pd.NaT, pd.Timestamp("1940-04-25"),
 pd.NaT]})

In [67]:
df1

       name  toy       born
0    Alfred  NaN        NaT
1    Batman  NaN 1940-04-25
2  Catwoman  NaN        NaT

In [68]:
df1.dropna(how='all',axis=1)

       name       born
0    Alfred        NaT
1    Batman 1940-04-25
2  Catwoman        NaT

In [69]:
df1

       name  toy       born
0    Alfred  NaN        NaT
1    Batman  NaN 1940-04-25
2  Catwoman  NaN        NaT

In [70]:
df2 = pd.DataFrame({"name": [np.nan, 'Batman', 'Catwoman'],
 "toy": [np.nan, 'Batmobile', 'Bullwhip'],
 "born": [pd.NaT, pd.Timestamp("1940-04-25"),
 pd.NaT]})

In [71]:
df2

       name        toy       born
0       NaN        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [72]:
df2.dropna(how='all')

       name        toy       born
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [73]:
df2

       name        toy       born
0       NaN        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [74]:
df3 = pd.DataFrame({"name": ['Alfred', 'Batman', 'Alfred'],
 "toy": [np.nan, 'Batmobile', 'Bullwhip'],
 "born": [pd.NaT, pd.Timestamp("1940-04-25"),
 pd.NaT]})

In [75]:
df3

     name        toy       born
0  Alfred        NaN        NaT
1  Batman  Batmobile 1940-04-25
2  Alfred   Bullwhip        NaT

In [76]:
df3.drop_duplicates(subset=['name']) #drop the row having duplicate value in column 'name'.Bydefault keep='first' is there which means first value will be kept and rest will be dropped.

     name        toy       born
0  Alfred        NaN        NaT
1  Batman  Batmobile 1940-04-25

In [77]:
df3.drop_duplicates(subset=['name'],keep='last') #droped duplicate value.Keeps second value

     name        toy       born
1  Batman  Batmobile 1940-04-25
2  Alfred   Bullwhip        NaT

In [78]:
df3.drop_duplicates(subset=['name'],keep=False) #droped all duplicate value from file.

     name        toy       born
1  Batman  Batmobile 1940-04-25

In [79]:
df3.shape # no. of rows and columns

(3, 3)

In [80]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   toy     2 non-null      str
 2   born    1 non-null      datetime64[us]
dtypes: datetime64[us](1), str(2)
memory usage: 204.0 bytes